name: Health check
on:
  schedule:
    # every hour
    - cron: '*/5 * * * *'
jobs:
  health:
    runs-on: ubuntu-22.04
    steps:
      - name: Check deployed site health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://lnxbudrvr-ci-cd-fso11.onrender.com/health
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
      
        
          
