name: Health check
on:
  schedule:
    # every hour
    - cron: '0 * * * *'
jobs:
  health:
    runs-on: ubuntu-22.04
    steps:
      - name: Check deployed site health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://lnxbudrvr-ci-cd-fso11.onrender.com/health
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
      

      - name: Inform success to Discord
        if: success()
        uses: Ilshidur/discord-webhook-action@0.3.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ✅ Health check ok
            URL: https://lnxbusdrvr-full-stack-open-pokedex.onrender.com/
            Time: ${{ github.event.schedule }}

      - name: Inform to Discord
        if: failure()
        uses: Ilshidur/discord-webhook-action@0.3.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ❌ Health check failed!
            URL: https://lnxbusdrvr-full-stack-open-pokedex.onrender.com/
            Time: ${{ github.event.schedule }}
        
          
